name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: install gtest
        run: sudo apt install -y libgtest-dev
      - name: test
        run: make test CC=gcc
